### ISSUE TITLE
April talk topic

### ISSUE THREAD

**Issue by garethellis36** [phpoxford/ideas#8]
What talk do we want Michael Heap (@mheap) to present at April's meet-up?

Please vote by +1ing the talk(s) you are interested in.

**Comment by mheap** [comment]
### Code Archaeology: Becoming Indiana Jones

Code archaeology is one of the most important skills you’ll ever learn as a developer. How many times have you been thrown into projects with no environment setup, no documentation, and very little support from coworkers? Being able to quickly work out how an application is structured so that you can start making changes is a sought after skill for many employers. 

In this talk, we’ll take an open source project that we’ve never seen before and work through the steps required to get it up and running so that we can start working on features. Once you know the steps, they can be applied to any project in any language to get you contributing in no time.

**Comment by mheap** [comment]
### Metrics and an application log: Your new best friends

Do you remember the time you spent an afternoon putting print statements in your app trying to debug an issue and removed them before shipping the fix, only to add them back in a day later to work on another issue? Wouldn't it be great if those debug statements could just stay in your code forever? Like a little gift that keeps on giving, not just for you, but for everyone else on your team too. 

That's what an application log is for! Logs aren't just for when things go wrong. They're for helping you to keep track of what's going on within your application. 

We take a look at how you can add helpful messages throughout your codebase and leave them there, even in production! We'll cover common logging strategies, log aggregation and how to efficiently work with your logs to get the data back out again. 

We'll also take a look at metrics solutions such as Graphite that can help augment your logs to help work out what was going on by correlating event logs with peaks/drops in other monitoring systems.

**Comment by mheap** [comment]
### Profiling your PHP application

So, you've been through and changed all your double quotes to single quotes but your application still isn't running at the speed of light. What's going on? 

Making an application scale is generally seen as something that only the most magical of developers can do, but it's easy once you have the correct tools. Fortunately for us, these tools are freely available online! 

In this talk, we'll take a look at a few options that we have available to work out what our application is actually doing, help identify bottlenecks and fix them so that we can move on to the more important part of the project: delivering features.

**Comment by garethellis36** [comment]
I'd be interested in the profiling or code archaeology talk.

**Comment by ascii-soup** [comment]
I'm interested in the "Metrics and an application log" talk since it fits with some work we always seem to get half-round to doing.

**Comment by mcidahechi** [comment]
I like the sound of all of them, but if I had to pick one, probably Metrics and an application log.

**Comment by garethellis36** [comment]
@mheap How much notice do you need on the talk topic?

**Comment by mheap** [comment]
@garethellis36 The end of this week would be good. I need to write most of them

**Comment by garethellis36** [comment]
OK, as you can see we have a fairly even split of votes so I'd say to just go ahead and choose the one that you'd rather practice.

**Comment by garethellis36** [comment]
@mheap ^^ - please let me know which talk you'd like to do.

**Comment by mheap** [comment]
Let's go for **Code Archaeology: Becoming Indiana Jones**
